[package]
name = "krpc-rust"
version = "0.1.0"
edition = "2021"


[dependencies]
#网络协议处理
tokio = { version = "1", features = ["full"] }
hyper = { version = "1.0.1", features = ["full"] }
http = "1.0.0"
http-body = "1.0.0"
http-body-util = "0.1.0"
bytes = "1"
futures = "0.3"
async-trait = "0.1.74"

#日志处理
tracing = "0.1.13"
tracing-futures = { version = "0.2.3" }
tracing-subscriber = "0.3.17"
pretty_env_logger = "0.5"

#json序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

pin-project-lite = "0.2.13"
lazy_static = "1"
