[package]
name = "examples"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true


[[bin]]
name = "server"
path = "src/server.rs"
[[bin]]
name = "client"
path = "src/client.rs"
[[bin]]
name = "client-pt"
path = "src/client_pt.rs"
[[bin]]
name = "dubbo-server"
path = "src/dubbo_server.rs"
[[bin]]
name = "dubbo-client"
path = "src/dubbo_client.rs"
[[bin]]
name = "dubbo-client-pt"
path = "src/dubbo_client_pt.rs"


[dependencies]
krpc-common = { path = "../krpc-common" }
krpc-core = { path = "../krpc-core"}
krpc-macro = { path = "../krpc-macro" }

#网络协议处理
tokio.workspace = true
hyper.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
bytes.workspace = true
futures.workspace = true
async-trait.workspace = true

#日志处理
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
pretty_env_logger.workspace = true

#json序列化
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

prost = "0.12.3"
prost-build = "0"

pin-project-lite.workspace = true
lazy_static.workspace = true
