[package]
name = "examples"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true


[[bin]]
name = "fusen-server"
path = "src/fusen/server.rs"
[[bin]]
name = "fusen-client"
path = "src/fusen/client.rs"

[[bin]]
name = "dubbo-server"
path = "src/dubbo/server.rs"
[[bin]]
name = "dubbo-client"
path = "src/dubbo/client.rs"

[[bin]]
name = "springcloud-server"
path = "src/springcloud/server.rs"
[[bin]]
name = "springcloud-client"
path = "src/springcloud/client.rs"


[dependencies]
fusen.workspace = true

#网络协议处理
tokio.workspace = true
hyper.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
bytes.workspace = true
futures.workspace = true
async-trait.workspace = true

#日志处理
tracing.workspace = true
tracing-futures.workspace = true
tracing-subscriber.workspace = true
pretty_env_logger.workspace = true

#json序列化
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

prost = "0.12.3"
prost-build = "0"

pin-project-lite.workspace = true
lazy_static.workspace = true
